API Reference
-------------

.. toctree::
   :maxdepth: 2

   api/modules

Additional Notes
----------------

Any additional notes that may help with usage, testing,
building, etc.


.. toctree::
   :maxdepth: 2

   testing
   documentation


Third Party Libraries
---------------------
{{ cookiecutter.project_slug }} depends on several libraries that are not documented within
these pages. If you'd like to read the documentation on those libraries
feel free to visit the links below:

- `example library Documentation`_

.. _`example library Documentation`: http://example.com/en/latest/


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
